import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/componets/header'
import { HistoryInput } from '@/componets/historyInput'
import { RegisterButton } from '@/componets/register-button'
import { HistoricButton } from '@/componets/historicButton'
import { FormImput } from '@/componets/formInput'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header/>
        <Link href="/register">Nova Página</Link>
        {children}
      </body>
    </html>
  )
}
