version: "3"

services:

    db:
        container_name: postgres
        image: "postgres" 
        ports:
          - 5432:5432
        env_file:
          - .env
        volumes:
          - postgres_data:/var/lib/postgresql/data 
        networks:
          - fluxstation-api
        deploy:
          resources:
            limits:
              cpus: '2'
              memory: 500M
            reservations:
              cpus: '1'
              memory: 200M
  
    api:
        container_name: api
        depends_on:
          - db
        build: ./micro-service/.
        ports:
          - 5000:3000
        networks:
          - fluxstation-api
        deploy:
          resources:
            limits:
              cpus: '2'
              memory: 500M
            reservations:
              cpus: '1'
              memory: 200M
    front:
        container_name: front-end
        build: ./frontend/.
        ports:
          - 3000:3000
        networks:
          - fluxstation-api
        deploy:
          resources:
            limits:
              cpus: '2'
              memory: 500M
            reservations:
              cpus: '1'
              memory: 200M

    nginx:
        container_name: nginx
        build: ./nginx-config/.
        ports:
          - 80:80
        networks:
          - fluxstation-api
        deploy:
          resources:
            limits:
              cpus: '2'
              memory: 500M
            reservations:
              cpus: '1'
              memory: 200M

          
volumes: 
    postgres_data:

      
networks:
  fluxstation-api: