site_name: Desafio FluxStation
repo_url: https://github.com/francisco1code/FluxStation


theme:
        name: material
        language: pt
        features:
                - navigation.tabs

nav:
        - Home: index.md
        - Desafio: desafio.md
        - Arquitetura: arquitetura.md
        - Backend: backend.md
        - Frontend: frontend.md